# Generated by Django 3.2.10 on 2023-08-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four')], max_length=10)),
                ('model', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='details',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
