# Generated by Django 3.2.10 on 2023-08-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20230810_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Super admin', 'Super admin'), ('Admin', 'Admin'), ('User', 'User')], max_length=20)),
            ],
        ),
    ]
