# Generated by Django 3.2.10 on 2023-08-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
